### PR TITLE
SDV-757 - calculate working days in the past

### PR DESCRIPTION
**Pull request by jeremyquinton**
Added method to calculate working days in past

### CODE REVIEW

**Comment by jeremyquinton** [comment]
Can achieve the same by calling a method with negative offset so closing PR

**Comment by brettminnie** [comment]
@jeremyquinton maybe add an alias method then that does converts the
positive increment to a negative, will be easier for someone else to use it
in future

**Comment by jeremyquinton** [comment]
@brettminnie we didn't merge this in the end you can just pass a negative value to the workingDaysFrom method
https://github.com/ministryofjustice/date-utils/blob/master/src/DateUtils/WorkingDays.php#L106

and it works! Bonus feature.

**Comment by eddiejaoude** [comment]
> ...just pass a negative value...

This doesn't sound good, random values are never clear.

I see two options here:

* Alias as suggested
* Easiest option is probably to pass in a static that has a value of `-1`, at least then it is descriptive :wink:

**Comment by jeremyquinton** [comment]
The method call looks like below
```
workingDaysFrom(new DateTime(), -20)
```
Which will give me 20 working days ago.

I don't see anything wrong with this. Its not a random value its a negative integer literal.

I think the alias is a good suggestion however we only need this method call for a step in a behat test and as the gherkin is descriptive this is good enough.

**Comment by eddiejaoude** [comment]
Sorry, I didn't realise it was an actual value - I thought it was just a flag. My bad, thanks for clarifying :smile:

**Comment by brettminnie** [comment]
I would have used the alias method to make it a bit more descriptive
something like


```
public function workingDaysInThePast($daysInPast)  {
   // abs to ensure we are multiplying a positive value by -1
    $daysInPast = abs($daysInPast) * -1;

  return $this->workingDaysFrom(new DateTime(), $daysInPast);

}

```

Would just simplify it for the end user

**Comment by jeremyquinton** [comment]
I'll accept a PR :-)

**Comment by brettminnie** [comment]
Cool, will knock one up at some point :)

**Pull request closed without merging**
